---
- import_tasks: pre-install.yml

- import_tasks: install.yml

- import_tasks: post-install.yml

- include_tasks: configure-ceph-for-zun.yml
  when:
    - zun_configure_for_cinder_ceph | bool
    - "'zun-compute' in group_names"
