---
# TODO(mgoddard): Remove this task in the A release.
- name: Fail if docker_custom_option is defined
  fail:
    msg: >-
      The 'docker_custom_option' variable has been removed. Please use
      'docker_custom_config' instead.
  when: docker_custom_option is defined

- include_tasks: "repo-{{ ansible_facts.os_family }}.yml"
  when: enable_docker_repo | bool

- import_tasks: install.yml

- import_tasks: config.yml

- include_tasks: configure-containerd-for-zun.yml
  when:
    - containerd_configure_for_zun|bool
    - "'zun-cni-daemon' in group_names"
