---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-rocky9
        - kolla-ansible-ubuntu
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-host-configure-ubuntu-jammy
    gate:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-rocky9
        - kolla-ansible-ubuntu
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-host-configure-ubuntu-jammy
