---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - kolla-ansible-centos8s-source
        - kolla-ansible-debian-source
        - kolla-ansible-ubuntu-source
        - kayobe-overcloud-centos8s
        - kayobe-overcloud-ubuntu-focal
        - kayobe-overcloud-host-configure-centos8s
        - kayobe-overcloud-host-configure-ubuntu-focal
    gate:
      jobs:
        - kolla-ansible-centos8s-source
        - kolla-ansible-debian-source
        - kolla-ansible-ubuntu-source
        - kayobe-overcloud-centos8s
        - kayobe-overcloud-ubuntu-focal
        - kayobe-overcloud-host-configure-centos8s
        - kayobe-overcloud-host-configure-ubuntu-focal
